# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180122_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=5000),
        ),
    ]
