# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followed_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='follows', to='registration.Profile'),
        ),
    ]
